export const COUNTRY_ACTION_START = "COUNTRY_ACTION_START";
export const COUNTRY_ACTION_ERROR = "COUNTRY_ACTION_ERROR";
export const COUNTRY_EDIT_SUCCESS = "COUNTRY_EDIT_SUCCESS";
export const COUNTRY_LOAD_SUCCESS = "COUNTRY_LOAD_SUCCESS";
export const COUNTRY_ADD_SUCCESS = "COUNTRY_ADD_SUCCESS";
export const COUNTRY_DELETE_SUCCESS = "COUNTRY_DELETE_SUCCESS";
